config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount API::Base, at: '/'
  resources :elders

  devise_for :users
  root to: 'home#index'
  devise_scope :user do
    get '/admin' => 'user#index'
    delete '/users/sign_out' => 'devise/sessions#destroy'
    get '/addTakecare' => 'user#caretaker'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/disease.rb
class Disease < ApplicationRecord
  belongs_to :elder
end

app/models/elder.rb
class Elder < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :diseases
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/relative.rb
class Relative < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

# To create the model of the Users
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_and_belongs_to_many :elders
end

app/controllers/api/base.rb
module API
  class Base < Grape::API
    mount API::V1::Base
  end
end

app/controllers/api/v1/base.rb
module API
  module V1
    class Base < Grape::API
      mount API::V1::Users
      mount API::V1::Elders
    end
  end
end

app/controllers/api/v1/defaults.rb
module API
  module V1
    module Defaults
      extend ActiveSupport::Concern

      included do
        prefix 'api'
        version 'v1', using: :path
        default_format :json
        format :json
        formatter :json,
          Grape::Formatter::ActiveModelSerializers

        helpers do
          def permitted_params
            @permitted_params ||= declared(params, include_missin: false)
          end

          def logger
            Rails.logger
          end
        end

        rescue_from ActiveRecord::RecordNotFound do |e|
          error_response(message: e.message, status: 404)
        end

        rescue_from ActiveRecord::RecordInvalid do |e|
          error_response(message: e.message, status: 422)
        end
      end
    end
  end
end

app/controllers/api/v1/elders.rb
module API
  module V1
    class Elders < Grape::API
      include API::V1::Defaults

      resource :elders do
        desc "Return all elders"
        get "", root: :elders do
          Elder.all
        end

        desc "Return a elder"
        params do
          requires :id, type: String, desc: "ID of the
            elder"
        end
        get ":id", root: "elder" do
          Elder.where(id: permitted_params[:id]).first!
        end        
      end
    end
  end
end

app/controllers/api/v1/users.rb
module API
  module V1
    class Users < Grape::API
      include API::V1::Defaults

      resource :users do
        desc "Return all users"
        get "", root: :users do
          User.all
        end

        desc "Return a user"
        params do
          requires :id, type: String, desc: "ID of the user"
        end
        get ":id", root: "user" do
          User.where(id: permitted_params[:id]).first!
        end

        desc "Return caretakers"
        params do
          requires :role_id, type: String, desc: "User's role"
        end
        get "role/:role_id", root: "user" do
          User.where(role: permitted_params[:role_id])
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/elders_controller.rb
# frozen_string_literal: true
class EldersController < ApplicationController
  before_action :set_elder, only: [:show, :edit, :update, :destroy]

  # GET /elders
  # GET /elders.json
  def index
    @elders = Elder.all
  end

  # GET /elders/1
  # GET /elders/1.json
  def show
  end

  # GET /elders/new
  def new
    @elder = Elder.new
  end

  # GET /elders/1/edit
  def edit
  end

  # POST /elders
  # POST /elders.json
  def create
    @elder = Elder.new(elder_params)

    respond_to do |format|
      if @elder.save
        format.html { redirect_to @elder, notice: 'Se añadió correctamente la información.' }
        format.json { render :show, status: :created, location: @elder }
      else
        format.html { render :new }
        format.json { render json: @elder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elders/1
  # PATCH/PUT /elders/1.json
  def update
    respond_to do |format|
      if @elder.update(elder_params)
        format.html { redirect_to @elder, notice: 'Se editó correctamente la información.' }
        format.json { render :show, status: :ok, location: @elder }
      else
        format.html { render :edit }
        format.json { render json: @elder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elders/1
  # DELETE /elders/1.json
  def destroy
    @elder.destroy
    respond_to do |format|
      format.html { redirect_to elders_url, notice: 'Se eliminó correctamente la información.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_elder
      @elder = Elder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def elder_params
      params.require(:elder).permit(:name, :first_name, :last_name, :blood_type, :birthdate, :weight, :height)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/user_controller.rb
# frozen_string_literal: true

# To control thw workflow in the user
class UserController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def index
    @elders = Elder.all
    render template: 'users/index'

  end

  def caretaker
    render template: 'users/form-takecare'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elders_helper.rb
module EldersHelper
end

app/views/elders/_form.html.haml
= form_with(model: elder, local: true) do |form|
  - if elder.errors.any?
    #error_explanation
      %h2
        = pluralize(elder.errors.count, "error")
        prohibited this elder from being saved:
      %ul
        - elder.errors.full_messages.each do |message|
          %li= message
  .elders__form-container.container.card
    .elders__field-container.card-body
      .elders__title
        = form.label 'Registro de adulto mayor.'
      .field
        = form.label :name, 'Nombre'
        = form.text_field :name, class:'form-control'
      .field
        = form.label :first_name, 'Apellido paterno'
        = form.text_field :first_name, class:'form-control'
      .field
        = form.label :last_name, 'Apellido materno'
        = form.text_field :last_name, class:'form-control'
      .field
        = form.label :blood_type, 'Tipo de sangre'
        = form.text_field :blood_type, class:'form-control'
      .field
        = form.label :birthdate, 'Fecha de nacimiento'
        = form.date_field :birthdate, class:'form-control'
      .field
        = form.label :weight, 'Peso'
        = form.text_field :weight, class:'form-control'
      .field
        = form.label :height, 'Estatura'
        = form.text_field :height, class:'form-control'
      .actions.elders__actions
        = link_to 'Regresar', elders_path, class:'btn btn-primary'
        = form.submit 'Añadir', class: 'btn btn-primary'

app/views/elders/edit.html.haml
%h1 Editar información
= render 'form', elder: @elder

app/views/elders/index.html.haml
.container.card.elder__index
  .card-body
    %p#notice= notice
    %h1.elder__index-title Adultos mayores
    %table.table.table-bordered
      %thead
        %tr
          %th Nombre
          %th Primer apellido
          %th Segundo apellido
          %th Tipo de sangre
          %th Fecha de nacimiento
          %th Peso
          %th Altura
          %th{colspan: "3"}
      %tbody
        - @elders.each do |elder|
          %tr
            %td= elder.name
            %td= elder.first_name
            %td= elder.last_name
            %td= elder.blood_type
            %td= elder.birthdate
            %td= elder.weight
            %td= elder.height
            %td= link_to 'Mostrar', elder
            %td= link_to 'Editar', edit_elder_path(elder)
            %td= link_to 'Eliminar', elder, method: :delete, data: { confirm: 'Are you sure?' }
    = link_to 'Añadir un adulto mayor', new_elder_path, class:'btn btn-primary'

app/views/elders/new.html.haml
%h1 Nuevo
= render 'form', elder: @elder

app/views/elders/show.html.haml
.container.card.elder__show-notice
  .card-body
    %p#notice
      = notice
    %p
      %strong Nombre:
      = @elder.name
    %p
      %strong Apellido paterno:
      = @elder.first_name
    %p
      %strong Apellido materno:
      = @elder.last_name
    %p
      %strong Tipo de sangre:
      = @elder.blood_type
    %p
      %strong Fecha de nacimiento:
      = @elder.birthdate
    %p
      %strong Peso:
      = @elder.weight
    %p
      %strong Altura:
      = @elder.height
.elders__actions
  = link_to 'Regresar', elders_path, class:'btn btn-primary'
  = link_to 'Editar', edit_elder_path(@elder), class:'btn btn-primary'

app/views/home/index.html.haml
= render 'partials/hero'
= render 'partials/about-us'
= render 'partials/how-it-works'
= render 'partials/contact-us'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title Abuelometro
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'partials/header'
    .container
      = yield
    = render 'partials/footer'

app/views/partials/_about-us.html.haml
.jumbotron.about-us-section
  %h2.display-5 Abuelometro, está aquí para ayudar
  %p.lead Somos una plataforma de monitoreo continuo para adultos mayores
  %hr.my-4
  %p A través de una aplicación móvil te damos acceso al estado de salud de tus familiares mayores de edad.
  %button#know-how.know-how-btn.btn ¿Cómo?

app/views/partials/_contact-us.html.haml
.jumbotron.contact-us-section
  %h2.display-5 ¡Trabajemos juntos!
  %p.lead En Abuelómetro te estamos esperando
  %hr.my-4
  %p Ponte en contacto con nosotros
  = link_to '¡Hablemos!', '/', class: 'lets-talk-btn btn'

app/views/partials/_footer.html.haml
%footer.footer__content
  %p.footer__company-motto Cuidemos de ellos juntos
  %ul.footer__links
    %li
      = link_to 'Home', '/'
    %li
      = link_to 'About us', '/'
    %li
      = link_to 'FAQ', '#'
    %li
      = link_to 'Contact us', '/contact-us'
  %p.footer__company-name MagmaHackers © 2018

app/views/partials/_header.html.haml
%nav.navbar.navbar-expand-lg.fixed-top
  = link_to '/', class: 'navbar-brand' do
    = image_tag('abuelometro_logo.png', alt: 'Abuelometro logo', class: 'navbar-logo')
    Abuelometro
  %button.navbar-toggler{ type: 'button', data: { toggle: 'collapse', target: '#navbarToggler'}, aria: { controls: 'navbarToggler', expanded: 'false', label: 'Toggle navigation'} }
    %span.navbar-toggler-icon
  #navbarToggler.collapse.navbar-collapse
    %ul.navbar-nav
      %li.nav-item
        - if user_signed_in?
          = link_to "Cerrar sesión", users_sign_out_path, :method => :delete, class:'nav-link'
        - else
          = link_to 'Iniciar sesión', '/admin', class: 'nav-link'
      %li.nav-item
        = link_to 'Acerca de nosotros', '/', class: 'nav-link'

app/views/partials/_hero.html.haml
.jumbotron.hero-section
  %h1.display-4 Cuidemos de ellos, juntos.
  %p.lead Ahora podrás estar más cerca
  %button#know-more.know-more-btn.btn Conoce más

app/views/partials/_how-it-works.html.haml
%section.how-it-works
  .container.how-it-works__container
    .how-it-works__inf
      %h1 Es muy sencillo

      .how-it-works__category
        .how-it-works__description
          = image_tag('login.png', alt: 'login', class: 'how-it-works__image')
          %h3 Captura
          %p Lorem ipsum dolor sit amet, consectetur adipisicing elit.

        .how-it-works__description
          = image_tag('login.png', alt: 'login', class: 'how-it-works__image')
          %h3 Captura
          %p Lorem ipsum dolor sit amet, consectetur adipisicing elit.

        .how-it-works__description
          = image_tag('login.png', alt: 'login', class: 'how-it-works__image')
          %h3 Captura
          %p Lorem ipsum dolor sit amet, consectetur adipisicing elit.

app/views/profiles/_form.html.haml
.card
  .card-body
    = form_with(model: profile, local: true) do |form|
      - if profile.errors.any?
        #error_explanation
          %h2
            = pluralize(profile.errors.count, "error")
            prohibited this profile from being saved:
          %ul
            - profile.errors.full_messages.each do |message|
              %li= message
      .form-group
        = form.label :profile_name
        = form.text_field :profile_name, class: "form-control"
      .form-group
        = form.label :profile_first_name
        = form.text_field :profile_first_name, class: "form-control"
      .form-group
        = form.label :profile_second_name
        = form.text_field :profile_second_name, class: "form-control"
      .form-group
        = form.label :profile_phone
        = form.text_field :profile_phone, class: "form-control"
      .form-group
        = form.submit class: 'btn grandpa-button'

app/views/profiles/edit.html.haml
%h1 Editing Profile
= render 'form', profile: @profile
= link_to 'Show', @profile
|
= link_to 'Back', profiles_path

app/views/profiles/index.html.haml
%p#notice= notice
%h1 Profiles
%table
  %thead
    %tr
      %th Profile name
      %th Profile first name
      %th Profile second name
      %th Profile phone
      %th{:colspan => "3"}
  %tbody
    - @profiles.each do |profile|
      %tr
        %td= profile.profile_name
        %td= profile.profile_first_name
        %td= profile.profile_second_name
        %td= profile.profile_phone
        %td= link_to 'Show', profile
        %td= link_to 'Edit', edit_profile_path(profile)
        %td= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Profile', new_profile_path

app/views/profiles/new.html.haml
%h1 New Profile
= render 'form', profile: @profile
= link_to 'Back', profiles_path

app/views/profiles/show.html.haml
%p#notice= notice
%p
  %strong Profile name:
  = @profile.profile_name
%p
  %strong Profile first name:
  = @profile.profile_first_name
%p
  %strong Profile second name:
  = @profile.profile_second_name
%p
  %strong Profile phone:
  = @profile.profile_phone
= link_to 'Edit', edit_profile_path(@profile)
|
= link_to 'Back', profiles_path

app/views/users/form-takecare.html.erb
<div class="form-container">
  <%= form_for :user,url: '/users',html: {class: 'form-horizontal'} do |t|%>
  <p>Email:</p>
  <input type="text" name="t[email]" value="<%= 'example@example.com' %>">
  <p>Password:</p>
  <input type="text" name="t[encrypted_password]">
  <p>Name:</p>
  <input type="text" name="t[name]">
  <p>First name:</p>
  <input type="text" name="t[first_name]">
  <p>Second name:</p>
  <input type="text" name="t[second_name]">
  <p>Phone number:</p>
  <input type="text" name="t[phone]">
  <input type="hidden" name="t[role]" value="<%= 2 %>">
  <div class='submit'><%= link_to('Save', admin_path)%></div>
  <% end %>'
</div>

app/views/users/index.haml
%br/
.homepage-admin
  .care-taker
    %a{:href => "#"}
      = image_tag('takecare',class: 'ico')
    %p.subtitle Cuidadores
    - @elders.each do |a|
      %p= a.name
  .elders
    %a{:href => "/elders"}
      %i.fa.fa-user.fa-2x
    %p.subtitle Adulto M
    - @elders.each do |a|
      %span= a.name
      %span= a.first_name
      %br/
  .diseases
    %a{:href => "#"}
      = image_tag('pils',class: 'ico')
    %p.subtitle Padecimientos
    %p Diabetes